### ISSUE TITLE
restart service if previously running

### ISSUE THREAD

**Issue by viceice** [AJDurant/choco-docker-engine#12]
I like to have the service automatically started after upgrades if it was running before

**Comment by AJDurant** [comment]
Because the service is stopped in the beforeModify script, there isn't an easy way to know if we need to start it or not. The best way to do this is to have a package param that defaults to not starting the service.

If you install / upgrade it with `--params "/StartService"` then it will attempt to start it for you now. If you have upgrade params remembered then this will apply on any upgrade too.

Hopefully that works for you @viceice

**Comment by viceice** [comment]
thanks, with remember params it should also work for further updates without params. 🤗

**Comment by viceice** [comment]
Doesn't work when service already exists.

I've send a PR to fix this:
- #16
