### ISSUE TITLE
use `dockerd --register-service` instead of `sc create`

### ISSUE THREAD

**Issue by viceice** [AJDurant/choco-docker-engine#5]
The recommend was to register the docker service is now `dockerd --register-service`[^1]

[^1]: https://docs.docker.com/engine/install/binaries/#install-server-and-client-binaries-on-windows

**Comment by AJDurant** [comment]
Yeah, it has been since before I made the package. The limitation is how Chocolatey tests packages, and the compatibility it requires. The verification tests run on Server 2012, and powershell is limited to V2. 2012 doesn't have container support with docker, so actually running docker itself fails. The powershell limitation is also why it uses `sc` instead of the cmdlets for services.

**Comment by viceice** [comment]
🙈 Even 2012 R2 is running out of support very soon. So thats a very bad limitation 😕 Is there any documentation about those limitations?

**Comment by AJDurant** [comment]
It is 2012 R2, some details about the test environment and package verifier are here: https://github.com/chocolatey-community/chocolatey-test-environment
